data:extend({
    {
        name = "wire-box-tool-mode",
        type = "string-setting",
        setting_type = "runtime-per-user",
        default_value = "red-green",
        allowed_values = { "red-green", "red-only", "green-only" },
    },
    {
        name = "alt-mode-electric-pole",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-container",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = true,
        per_user = true,
    },
    {
        name = "alt-mode-mining-drill",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = true,
        per_user = true,
    },
    {
        name = "alt-mode-inserter",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-lamp",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-transport-belt",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-logistic-container",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-storage-tank",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-gate",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-pump",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-offshore-pump",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = true,
        per_user = true,
    },
    {
        name = "alt-mode-accumulator",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-rail-signal",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-rail-chain-signal",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-power-switch",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-programmable-speaker",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-train-stop",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    },
    {
        name = "alt-mode-roboport",
        type = "bool-setting",
        setting_type = "runtime-per-user",
        default_value = false,
        per_user = false,
    }
})
